/**
 * A page: a URL, its search-result text, and an ordered list of blocks.
 *
 * This is the builder. Unlike `pageCopy`, which only filled in slots a
 * template had already decided on, a page document owns its own shape —
 * blocks can be added, reordered and deleted, and the site renders whatever
 * is here through the catch-all route in `src/pages/[...slug].astro`.
 *
 * THE SLUG IS THE URL AND CHANGING IT BREAKS LINKS. Sanity will happily let
 * you rename `spring-showreel` to `showreel`; every link anyone has shared to
 * the old address then 404s. Rename only before a page has been published
 * anywhere, and if you must rename later, tell whoever owns the redirects.
 *
 * RESERVED ROUTES. The blog, portfolio, services, careers and case-study
 * routes are generated by their own templates and are NOT built from this
 * type. A page whose slug collides with one of them would never render,
 * because a file route always wins over the catch-all — so the slug field
 * refuses those prefixes rather than letting someone build a page that
 * silently never appears.
 */
import { defineType, defineField } from 'sanity';
import { blockArrayMembers } from './blocks';
import { SeoPanel } from '../components/SeoPanel';

/**
 * Prefixes owned by a real template.
 *
 * Kept in step with `src/pages/` by hand. Getting it wrong is not dangerous —
 * the file route wins either way — it just means the Studio fails to warn.
 */
const RESERVED = [
  'blog',
  'portfolio',
  'services',
  'careers',
  'case-studies',
  'admin',
  'search.json',
  '404',
];

export default defineType({
  name: 'page',
  title: 'Built page',
  type: 'document',

  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'seo', title: 'Search & sharing' },
  ],

  fields: [
    defineField({
      name: 'title',
      title: 'Page name',
      type: 'string',
      group: 'content',
      description:
        'For your own reference in this list. Not shown on the page — the hero block carries the visible headline.',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'slug',
      title: 'URL',
      type: 'slug',
      group: 'content',
      description: 'The address, after the domain. "spring-showreel" becomes /spring-showreel/.',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: (input) =>
          input
            .toLowerCase()
            .trim()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '')
            .slice(0, 96),
      },
      validation: (Rule) =>
        Rule.required().custom((value) => {
          const current = typeof value === 'object' && value ? value.current : undefined;
          if (!current) return 'A page needs a URL.';
          const first = current.split('/')[0];
          if (RESERVED.includes(first)) {
            return `"${first}" is generated by its own template — a page here would never appear. Pick another URL.`;
          }
          return true;
        }),
    }),

    defineField({
      name: 'blocks',
      title: 'Sections',
      type: 'array',
      group: 'content',
      of: blockArrayMembers,
      description:
        'The page, top to bottom. Drag to reorder. Most pages open with a hero and close with a call to action.',
      validation: (Rule) => Rule.required().min(1).error('A page needs at least one section.'),
    }),

    /* ---------------------------------------------------------------- */
    /* Search and sharing                                                */
    /* ---------------------------------------------------------------- */
    /**
     * The focus keyphrase.
     *
     * STORED, NEVER PUBLISHED. `<meta name="keywords">` has been ignored by
     * Google since 2009, and this does not become one — it exists so the panel
     * below has something to check the page against. Yoast's focus keyphrase
     * works exactly the same way, which surprises almost everybody.
     *
     * One phrase, not a list. The checks ask whether the page is ABOUT this
     * thing — is it in the title, the first paragraph, a heading — and a comma-
     * separated list of six makes every one of those questions meaningless.
     */
    defineField({
      name: 'focusKeyphrase',
      title: 'Focus keyphrase',
      type: 'string',
      group: 'seo',
      description:
        'What somebody would type into Google to find this page — "3d character art outsourcing", not "art". Never published: it only drives the checks below.',
      validation: (Rule) =>
        Rule.max(60).warning('That reads more like a sentence than something anybody searches for.'),
    }),

    /**
     * The preview and the checks.
     *
     * A synthetic field: it stores nothing, and its input component reads the
     * whole document instead. `readOnly` keeps the form machinery from
     * expecting a value, and the empty title stops the Studio drawing a label
     * above a panel that is clearly its own thing.
     */
    defineField({
      name: 'seoPreview',
      title: 'Preview and checks',
      type: 'string',
      group: 'seo',
      readOnly: true,
      components: { input: SeoPanel },
    }),

    defineField({
      name: 'seoTitle',
      title: 'Search-result title',
      type: 'string',
      group: 'seo',
      description:
        'The blue line in Google and the browser tab. Google truncates around 60 characters, so put the page first and the studio name last.',
      validation: (Rule) =>
        Rule.required().max(70).warning('Over ~60 characters usually gets cut off in search results.'),
    }),
    defineField({
      name: 'seoDescription',
      title: 'Search-result description',
      type: 'text',
      rows: 3,
      group: 'seo',
      description:
        'The grey paragraph under the title in Google. Write it as a reason to click, not a summary of the markup.',
      validation: (Rule) =>
        Rule.required()
          .max(300)
          .warning('Google cuts this around 160 characters — the rest is indexed, just not shown.'),
    }),
    defineField({
      name: 'ogImage',
      title: 'Sharing image',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
      description:
        'Shown when the page is pasted into WhatsApp, Slack or LinkedIn. Cropped to 1200x630 — set the hotspot so the crop keeps what matters.',
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'string',
      group: 'seo',
      description:
        'Leave blank unless this page duplicates another on purpose. Then put the URL of the one that should rank — a full https:// address, or a path on this site.',
      validation: (Rule) =>
        Rule.custom((v: string | undefined) =>
          !v || /^(\/|https?:\/\/)/.test(v)
            ? true
            : 'Use a path starting with / or a full http(s) URL.'
        ),
    }),
    defineField({
      name: 'noindex',
      title: 'Hide from search engines',
      type: 'boolean',
      group: 'seo',
      description:
        'For a page you want to share by link but not have found — a client review page, an unlisted campaign. It does NOT make the page private: anyone with the URL can still open it.',
      initialValue: false,
    }),
  ],

  preview: {
    select: { title: 'title', slug: 'slug.current', blocks: 'blocks' },
    prepare: ({ title, slug, blocks }) => ({
      title,
      subtitle: `/${slug ?? '?'}/  ·  ${(blocks ?? []).length} section(s)`,
    }),
  },
});
